#!/bin/bash

###############################################################################
# Migration Report Generator
#
# Generates a comprehensive migration report documenting:
# - Migration metadata (versions, dates, duration)
# - Complexity analysis results
# - Pattern detection findings
# - Files changed during migration
# - Conflicts resolved
# - Build verification results
# - Custom features verified
# - Recommendations for next steps
#
# Usage:
#   ./scripts/generate-migration-report.sh [migration-branch-name]
#   ./scripts/generate-migration-report.sh migration/4.0-to-9.1
###############################################################################

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Configuration
MIGRATION_BRANCH=${1:-$(git branch --show-current)}
REPORT_DATE=$(date +%Y-%m-%d)
REPORT_FILE="migration-report-${REPORT_DATE}.md"

echo -e "${CYAN}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║${NC}      ${BLUE}Migration Report Generator${NC}                            ${CYAN}║${NC}"
echo -e "${CYAN}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""

###############################################################################
# Helper Functions
###############################################################################

get_package_version() {
  local package=$1
  grep "\"$package\"" package.json | head -1 | cut -d'"' -f4 || echo "N/A"
}

get_git_log_summary() {
  local base_branch=$1
  local target_branch=$2
  
  if git rev-parse "$base_branch" >/dev/null 2>&1 && git rev-parse "$target_branch" >/dev/null 2>&1; then
    git log --oneline "${base_branch}..${target_branch}" 2>/dev/null | wc -l
  else
    echo "N/A"
  fi
}

count_files_changed() {
  local base_branch=$1
  local target_branch=$2
  
  if git rev-parse "$base_branch" >/dev/null 2>&1 && git rev-parse "$target_branch" >/dev/null 2>&1; then
    git diff --stat "${base_branch}...${target_branch}" 2>/dev/null | tail -1 | awk '{print $1}' || echo "N/A"
  else
    echo "N/A"
  fi
}

###############################################################################
# Collect Migration Data
###############################################################################

echo -e "${BLUE}📊 Collecting migration data...${NC}\n"

# Get current branch info
CURRENT_BRANCH=$(git branch --show-current)
CURRENT_COMMIT=$(git rev-parse --short HEAD)

# Try to detect source and target versions
ANGULAR_VERSION=$(get_package_version "@angular/core")
PWA_VERSION=$(get_package_version "version")

# Check for existing reports
PATTERN_REPORT="pattern-detection-report.json"
I18N_REPORT="i18n-merge-report.json"
COMPLEXITY_REPORT=".migration-complexity.json"

# Build status
echo -e "${YELLOW}Checking build status...${NC}"
BUILD_STATUS="Unknown"
BUILD_OUTPUT=""
if command -v npm &> /dev/null; then
  if npm run build > /tmp/build-check.log 2>&1; then
    BUILD_STATUS="✅ Success"
    BUILD_OUTPUT="Build completed successfully"
  else
    BUILD_STATUS="❌ Failed"
    BUILD_OUTPUT=$(tail -20 /tmp/build-check.log)
  fi
fi

# Test status
echo -e "${YELLOW}Checking test status...${NC}"
TEST_STATUS="Unknown"
TEST_OUTPUT=""
if command -v npm &> /dev/null; then
  if npm test -- --passWithNoTests > /tmp/test-check.log 2>&1; then
    TEST_STATUS="✅ Success"
    TEST_OUTPUT="All tests passed"
  else
    TEST_STATUS="⚠️ Some issues"
    TEST_OUTPUT=$(tail -20 /tmp/test-check.log)
  fi
fi

# Lint status
echo -e "${YELLOW}Checking lint status...${NC}"
LINT_STATUS="Unknown"
LINT_ERRORS=0
LINT_WARNINGS=0
if command -v npm &> /dev/null && [ -f "package.json" ]; then
  if npm run lint > /tmp/lint-check.log 2>&1; then
    LINT_STATUS="✅ No issues"
  else
    LINT_STATUS="⚠️ Issues found"
    LINT_ERRORS=$(grep -c "error" /tmp/lint-check.log 2>/dev/null || echo 0)
    LINT_WARNINGS=$(grep -c "warning" /tmp/lint-check.log 2>/dev/null || echo 0)
  fi
fi

# Count custom features
CUSTOM_EXTENSIONS=$(find src/app/extensions -maxdepth 1 -type d 2>/dev/null | tail -n +2 | wc -l || echo 0)
CUSTOM_THEMES=$(find src/styles/themes -maxdepth 1 -type d 2>/dev/null | tail -n +2 | wc -l || echo 0)
CUSTOM_COMPONENTS=$(find src/app -name "*.component.ts" -type f 2>/dev/null | wc -l || echo 0)

###############################################################################
# Generate Report
###############################################################################

echo -e "${BLUE}📝 Generating report: ${REPORT_FILE}${NC}\n"

cat > "$REPORT_FILE" << EOF
# PWA Migration Report

**Date:** ${REPORT_DATE}  
**Migration Branch:** \`${MIGRATION_BRANCH}\`  
**Current Commit:** \`${CURRENT_COMMIT}\`  
**Generated by:** Migration Report Generator v1.0

---

## Executive Summary

This report documents the migration of the Intershop PWA customization project.

### Quick Status

| Aspect | Status |
|--------|--------|
| **Build** | ${BUILD_STATUS} |
| **Tests** | ${TEST_STATUS} |
| **Lint** | ${LINT_STATUS} |
| **Overall** | $([ "$BUILD_STATUS" = "✅ Success" ] && echo "✅ Ready for review" || echo "⚠️ Needs attention") |

---

## Migration Details

### Versions

- **Angular Version:** ${ANGULAR_VERSION}
- **PWA Version:** ${PWA_VERSION}
- **Node Version:** $(node --version 2>/dev/null || echo "N/A")
- **npm Version:** $(npm --version 2>/dev/null || echo "N/A")

### Timeline

- **Report Generated:** ${REPORT_DATE}
- **Branch Created:** $(git log --reverse --format="%ci" "${MIGRATION_BRANCH}" 2>/dev/null | head -1 | cut -d' ' -f1 || echo "N/A")
- **Last Commit:** $(git log -1 --format="%ci" 2>/dev/null | cut -d' ' -f1 || echo "N/A")

---

## Customization Summary

### Custom Features

- **Custom Extensions:** ${CUSTOM_EXTENSIONS}
$([ -d "src/app/extensions" ] && find src/app/extensions -maxdepth 1 -type d 2>/dev/null | tail -n +2 | sed 's|.*/|  - |' || echo "  - None detected")

- **Custom Themes:** ${CUSTOM_THEMES}
$([ -d "src/styles/themes" ] && find src/styles/themes -maxdepth 1 -type d 2>/dev/null | tail -n +2 | sed 's|.*/|  - |' || echo "  - None detected")

- **Total Components:** ${CUSTOM_COMPONENTS}

EOF

# Add pattern detection results if available
if [ -f "$PATTERN_REPORT" ]; then
  cat >> "$REPORT_FILE" << EOF

---

## Pattern Detection Results

EOF
  
  # Parse JSON report
  if command -v jq &> /dev/null; then
    TOTAL_PATTERNS=$(jq '.results | length' "$PATTERN_REPORT" 2>/dev/null || echo 0)
    TOTAL_OCCURRENCES=$(jq '[.results[].matchCount] | add // 0' "$PATTERN_REPORT" 2>/dev/null || echo 0)
    
    cat >> "$REPORT_FILE" << EOF
**Pattern Analysis Mode:** $(jq -r '.mode // "N/A"' "$PATTERN_REPORT" 2>/dev/null)  
**Patterns Detected:** ${TOTAL_PATTERNS}  
**Total Occurrences:** ${TOTAL_OCCURRENCES}

### Detected Patterns

EOF
    
    # List each pattern
    jq -r '.results[] | "#### " + .pattern.description + "\n\n- **Type:** " + .pattern.type + "\n- **Occurrences:** " + (.matchCount | tostring) + "\n- **Severity:** " + (.pattern.severity // "medium") + "\n" + (if .pattern.requiresImport then "- **Requires:** `" + .pattern.requiresImport + "`\n" else "" end) + "\n**Files affected:**\n" + ([.matches[].file | "- `" + . + "`"] | unique | join("\n")) + "\n"' "$PATTERN_REPORT" 2>/dev/null >> "$REPORT_FILE" || echo "- Error parsing pattern details" >> "$REPORT_FILE"
  else
    echo "**Note:** Install \`jq\` for detailed pattern analysis." >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
    echo "\`\`\`" >> "$REPORT_FILE"
    cat "$PATTERN_REPORT" >> "$REPORT_FILE"
    echo "\`\`\`" >> "$REPORT_FILE"
  fi
else
  cat >> "$REPORT_FILE" << EOF

---

## Pattern Detection Results

**Status:** No pattern detection report found.

Run pattern detection with:
\`\`\`bash
./scripts/detect-pattern-changes.js [source-version] [target-version]
\`\`\`

EOF
fi

# Add i18n merge results if available
if [ -f "$I18N_REPORT" ]; then
  cat >> "$REPORT_FILE" << EOF

---

## Localization Merge Results

EOF
  
  if command -v jq &> /dev/null; then
    TOTAL_CONFLICTS=$(jq '[.locales[].conflicts | length] | add // 0' "$I18N_REPORT" 2>/dev/null || echo 0)
    SEMANTIC_CONFLICTS=$(jq '[.locales[].stats.semanticConflicts] | add // 0' "$I18N_REPORT" 2>/dev/null || echo 0)
    
    cat >> "$REPORT_FILE" << EOF
**Total Conflicts:** ${TOTAL_CONFLICTS}  
**Semantic Conflicts:** ${SEMANTIC_CONFLICTS}  
**Locales Processed:** $(jq '.summary.totalLocales // 0' "$I18N_REPORT" 2>/dev/null)

### Merge Details

EOF
    
    jq -r '.locales[] | "#### " + .locale + "\n\n- **Total keys:** " + (.stats.total | tostring) + "\n- **Custom only:** " + (.stats.customOnly | tostring) + "\n- **PWA only:** " + (.stats.pwaOnly | tostring) + "\n- **Semantic conflicts:** " + (.stats.semanticConflicts | tostring) + "\n"' "$I18N_REPORT" 2>/dev/null >> "$REPORT_FILE" || echo "- Error parsing i18n details" >> "$REPORT_FILE"
  else
    echo "**Note:** Install \`jq\` for detailed localization analysis." >> "$REPORT_FILE"
  fi
else
  cat >> "$REPORT_FILE" << EOF

---

## Localization Merge Results

**Status:** No localization merge report found.

Localization files were handled using standard git merge strategies.

EOF
fi

# Add build and verification results
cat >> "$REPORT_FILE" << EOF

---

## Build & Verification Results

### Build Status

**Result:** ${BUILD_STATUS}

\`\`\`
${BUILD_OUTPUT}
\`\`\`

### Test Status

**Result:** ${TEST_STATUS}

\`\`\`
${TEST_OUTPUT}
\`\`\`

### Lint Status

**Result:** ${LINT_STATUS}

$([ "$LINT_STATUS" != "✅ No issues" ] && echo "- **Errors:** ${LINT_ERRORS}" || echo "")
$([ "$LINT_STATUS" != "✅ No issues" ] && echo "- **Warnings:** ${LINT_WARNINGS}" || echo "")

---

## Files Changed

EOF

# Try to get files changed if we can determine base branch
if git show-ref --verify --quiet refs/heads/develop; then
  BASE_BRANCH="develop"
elif git show-ref --verify --quiet refs/heads/main; then
  BASE_BRANCH="main"
else
  BASE_BRANCH=""
fi

if [ -n "$BASE_BRANCH" ]; then
  FILES_CHANGED=$(count_files_changed "$BASE_BRANCH" "$MIGRATION_BRANCH")
  COMMITS=$(get_git_log_summary "$BASE_BRANCH" "$MIGRATION_BRANCH")
  
  cat >> "$REPORT_FILE" << EOF
**Base Branch:** \`${BASE_BRANCH}\`  
**Files Changed:** ${FILES_CHANGED}  
**Commits:** ${COMMITS}

### Top Changed Files

\`\`\`
$(git diff --stat "${BASE_BRANCH}...${MIGRATION_BRANCH}" 2>/dev/null | head -20 || echo "Unable to determine file changes")
\`\`\`

EOF
else
  cat >> "$REPORT_FILE" << EOF
**Note:** Unable to determine base branch for comparison.

Run \`git diff --stat [base-branch]...[migration-branch]\` to see changes.

EOF
fi

# Add recommendations section
cat >> "$REPORT_FILE" << EOF

---

## Next Steps & Recommendations

EOF

if [ "$BUILD_STATUS" = "✅ Success" ]; then
  cat >> "$REPORT_FILE" << EOF
### ✅ Build Successful

Your migration build is successful! Recommended next steps:

1. **Review Migration Changes**
   \`\`\`bash
   git diff ${BASE_BRANCH:-develop}...${MIGRATION_BRANCH} --stat
   \`\`\`

2. **Manual Testing**
   - [ ] Test custom features functionality
   - [ ] Verify all pages render correctly
   - [ ] Check custom theme appearance
   - [ ] Test B2B features (if applicable)
   - [ ] Verify custom extensions work

3. **Share Migration (Choose Your Workflow)**
   
   **Option A: Keep Local (Testing Only)**
   \`\`\`bash
   # Continue testing locally without pushing
   npm run start
   # When satisfied, merge locally or create patch
   \`\`\`
   
   **Option B: Push to Remote (Team Review)**
   \`\`\`bash
   # Push migration branch for team review
   git push origin ${MIGRATION_BRANCH}
   # Then create PR/MR in your Git hosting platform
   \`\`\`
   
   **Option C: Create Patch File (Share Offline)**
   \`\`\`bash
   # Create patch for email/file sharing
   git format-patch ${BASE_BRANCH:-develop}..${MIGRATION_BRANCH} -o patches/
   \`\`\`

4. **Update Documentation**
   - [ ] Update CHANGELOG.md with migration notes
   - [ ] Document any custom code changes
   - [ ] Note any breaking changes for team

EOF
else
  cat >> "$REPORT_FILE" << EOF
### ⚠️ Build Issues Detected

The build is not yet successful. Recommended actions:

1. **Review Build Errors**
   \`\`\`bash
   npm run build 2>&1 | tee build-errors.log
   \`\`\`

2. **Check Pattern Detection Report**
   $([ -f "$PATTERN_REPORT" ] && echo "Review \`${PATTERN_REPORT}\` for patterns that need fixing" || echo "Run \`./scripts/detect-pattern-changes.js\` to identify issues")

3. **Common Issues to Check**
   - [ ] SCSS variables missing in custom theme
   - [ ] Environment features not registered
   - [ ] Import statements need updating
   - [ ] Deprecated patterns need replacement

4. **Consult Migration Guides**
   - See \`.github/instructions/migration-issues.instructions.md\`
   - Review \`.github/instructions/migration-workflow.instructions.md\`

EOF
fi

# Add lint recommendations if needed
if [ "$LINT_STATUS" != "✅ No issues" ]; then
  cat >> "$REPORT_FILE" << EOF

### 🔧 Lint Issues

Fix lint issues before finalizing:

\`\`\`bash
npm run lint -- --fix
\`\`\`

Review remaining issues:
\`\`\`bash
npm run lint > lint-report.txt
./scripts/check-lint-issues.sh
\`\`\`

EOF
fi

# Footer
cat >> "$REPORT_FILE" << EOF

---

## Additional Resources

- **Migration Instructions:** \`.github/instructions/\`
- **Pattern Detection Guide:** \`.github/instructions/migration-pattern-detection.instructions.md\`
- **Git Strategies:** \`.github/instructions/migration-git.instructions.md\`
- **Common Issues:** \`.github/instructions/migration-issues.instructions.md\`

---

*Report generated by: PWA Migration Toolkit*  
*Timestamp: $(date)*
EOF

###############################################################################
# Done
###############################################################################

echo -e "${GREEN}✅ Migration report generated: ${REPORT_FILE}${NC}\n"
echo -e "${CYAN}Preview:${NC}"
echo -e "${YELLOW}────────────────────────────────────────────────────────────────${NC}"
head -50 "$REPORT_FILE"
echo -e "${YELLOW}────────────────────────────────────────────────────────────────${NC}"
echo -e "\n${BLUE}View full report:${NC} cat ${REPORT_FILE}"
echo -e "${BLUE}Or open in editor:${NC} code ${REPORT_FILE}\n"
